name: Build and publish spikeinterface_pipelines Pyton package

on:
  push:
    branches:
      - main
    paths:
      - src/spikeinterface_pipelines/**

jobs:
  pypi-release:
    name: PyPI release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install twine
      - name: Build and publish to PyPI
        run: |
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
